<a href="https://colab.research.google.com/github/callmeeric5/Epita_AIS/blob/main/NLP/session1/assignment/course1_LDA_NMF_ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import io
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.decomposition import LatentDirichletAllocation, NMF
from google.colab import files

## Data loading

In [ ]:
# Mounting the google drive to google colab in order to load the data files directly from it
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# The data can be load directly from it
# You must change the path if the data is not directly in the path EPITA_NLP/Course1/ of the google drive
quora = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/NLP/Session1/quora_questions.csv')
print(quora.head(30))
# We consider only yhe 10000 first files in order to decrease the computation time
texts = quora["Question"][0:10000]

                                             Question
0   What is the step by step guide to invest in sh...
1   What is the story of Kohinoor (Koh-i-Noor) Dia...
2   How can I increase the speed of my internet co...
3   Why am I mentally very lonely? How can I solve...
4   Which one dissolve in water quikly sugar, salt...
5   Astrology: I am a Capricorn Sun Cap moon and c...
6                                 Should I buy tiago?
7                      How can I be a good geologist?
8                     When do you use シ instead of し?
9   Motorola (company): Can I hack my Charter Moto...
10  Method to find separation of slits using fresn...
11        How do I read and find my YouTube comments?
12               What can make Physics easy to learn?
13        What was your first sexual experience like?
14  What are the laws to change your status from a...
15  What would a Trump presidency mean for current...
16                       What does manipulation mean?
17  Why do girls want to be 

## Non-negative Matrix Factorization

Pre-processing

Use the TfidfVectorizer function : https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html

In [ ]:
# Question 1: Uncomment and complete the following lines

tfidf = TfidfVectorizer()
dtm = tfidf.fit_transform(texts)

Use of the NMF algorithm

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.NMF.html

In [ ]:
# Question 2: Uncomment and complete the following lines (choose the number of components you want)

NMF_ = NMF(n_components=7,random_state = 42)
NMF_.fit(dtm)

NMF(n_components=7, random_state=42)

Have a look at the components


In [ ]:
NMF_.components_

array([[0.00133646, 0.00045905, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01052306, 0.00107959, 0.        , ..., 0.00185695, 0.00185695,
        0.        ],
       [0.        , 0.        , 0.00198701, ..., 0.        , 0.        ,
        0.00090948],
       ...,
       [0.0030841 , 0.        , 0.        , ..., 0.00217287, 0.00217287,
        0.0030993 ],
       [0.01383832, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.00032838, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

Have a look at the shape of the component array.

Can you explain the meaning of the shape observed?


In [ ]:
NMF_.components_.shape, type(NMF_.components_)

((7, 11738), numpy.ndarray)

Let's have a look at the most representative words of each topic


In [ ]:
# Question 3: Print the 15 words the most representative of each topic
# Advice: both tfidf and NMF_ objects can be useful to achieve it
feature_names = tfidf.get_feature_names_out()
# For each topic, get the top 15 words
for topic_idx, topic in enumerate(NMF_.components_):
    print(f"Topic #{topic_idx + 1}:")
    top_words_idx = topic.argsort()[-16:-1] # Get indices of top 15 words
    top_words = [feature_names[i] for i in top_words_idx]
    print(" ".join(top_words))

# Do you think the number of components used at the previous question for the NMF was relevant? You can try to change it if you want.

Topic #1:
meaning 500 world most who will life india difference in between and what of is
Topic #2:
where english find we for from improve on money make in get do my can
Topic #3:
on books most that about things ways movies in the good examples of what some
Topic #4:
when someone thing that ever what have about would know how think if your do
Topic #5:
feel want mean have possible an should learn way what is like be does it
Topic #6:
ever under to 2016 language india learn book what way in is for which the
Topic #7:
and believe trump we did or questions have should on not so quora do people


Associate explicitly each text to a topic

In [ ]:
# Question 4: associate each text to a specific topic into a new two-column DataFrame
# with one column for the text and the other for the topic number
# Hint: you may find NMF_.transform function useful
import numpy as np
W = NMF_.fit_transform(dtm)
topic_assignments = np.argmax(W, axis=1)
print(topic_assignments)
texts_topics_df = pd.DataFrame({'Text': texts, 'Topic': topic_assignments})

texts_topics_df.head()

[4 0 1 ... 0 5 2]


Text  Topic
0  What is the step by step guide to invest in sh...      4
1  What is the story of Kohinoor (Koh-i-Noor) Dia...      0
2  How can I increase the speed of my internet co...      1
3  Why am I mentally very lonely? How can I solve...      6
4  Which one dissolve in water quikly sugar, salt...      5

## Latent Dirichlet Allocation (LDA)

Pre-processing

Use the CountVectorizer function : https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [ ]:
# Question 5: Uncomment and complete the following lines

cv = CountVectorizer()
dtm = cv.fit_transform(texts)

Use of the LDA algorithm

https://scikit-learn.org/stable/modules/generated/sklearn.decomposition.LatentDirichletAllocation.html

In [ ]:
# Question 6: Uncomment and complete the following lines (choose the number of components you want)

LDA = LatentDirichletAllocation(n_components=7,random_state=42)
LDA.fit(dtm)

LatentDirichletAllocation(n_components=7, random_state=42)

Have a look at the components



In [ ]:
LDA.components_

array([[ 2.18345094,  0.14285723,  0.14285722, ...,  0.14372308,
         0.14372308,  0.14285743],
       [ 0.14286791,  0.14285721,  0.1428572 , ...,  0.14285735,
         0.14285735,  0.14324155],
       [ 3.101842  ,  0.14285727,  0.14285725, ...,  0.14393173,
         0.14393173,  0.14285758],
       ...,
       [13.58218375,  0.14285722,  0.14332298, ...,  0.14285739,
         0.14285739,  1.1424711 ],
       [ 1.1541931 ,  0.14285724,  1.14239093, ...,  0.14285746,
         0.14285746,  0.14285748],
       [ 0.14367242,  0.14309098,  0.14285721, ...,  0.14285741,
         0.14285741,  0.14285744]])

Have a look at the shape of the component array.

Can you explain the meaning of the shape observed?

In [ ]:
LDA.components_.shape

(7, 11738)

Let's have a look at the most representative words of each topic


In [ ]:
# Question 6: Print the 15 words the most representative of each topic
# Advice: both cv and LDA objects can be useful to achieve it
feature_names = cv.get_feature_names_out()
# For each topic, get the top 15 words
for topic_idx, topic in enumerate(LDA.components_):
    print(f"Topic #{topic_idx + 1}:")
    top_words_idx = topic.argsort()[-16:-1] # Get indices of top 15 words
    top_words = [feature_names[i] for i in top_words_idx]
    print(" ".join(top_words))


# Do you think the number of components used at the previous question for the LDA was relevant? You can try to change it if you want.

Topic #1:
for would on why will if of in what is and to how do you
Topic #2:
which be way are does how of and best for it in to what the
Topic #3:
improve where was be and does to of get the my why do in how
Topic #4:
or you your which why for difference best between are in of and is what
Topic #5:
good india and most can to which is for best some of in the are
Topic #6:
you or for it that the if quora do on my how is why can
Topic #7:
does have in get and me make should with what you to my can do


Associate explicitly each text to a topic

In [ ]:
# Question 7: associate each text to a specific topic into a new three-column DataFrame
# with one column for the text, the second for the topic number of NMF classification and the third  for the topic number of LDA classification
# Hint: you may find LDA.transform function useful
M = LDA.transform(dtm)
topic_assignments_lda = np.argmax(M, axis=1)
print(topic_assignments)
texts_topics_lda_df = pd.DataFrame({'Text': texts, 'Topic': topic_assignments_lda})

texts_topics_lda_df.head()

[4 0 1 ... 0 5 2]


Text  Topic
0  What is the step by step guide to invest in sh...      4
1  What is the story of Kohinoor (Koh-i-Noor) Dia...      4
2  How can I increase the speed of my internet co...      5
3  Why am I mentally very lonely? How can I solve...      6
4  Which one dissolve in water quikly sugar, salt...      3

In [ ]:
final_df = texts_topics_df.merge(texts_topics_lda_df, on = 'Text')
final_df.head()

Text  Topic_x  Topic_y
0  What is the step by step guide to invest in sh...        4        4
1  What is the story of Kohinoor (Koh-i-Noor) Dia...        0        4
2  How can I increase the speed of my internet co...        1        5
3  Why am I mentally very lonely? How can I solve...        6        6
4  Which one dissolve in water quikly sugar, salt...        5        3